{
  proyectos {
    nodes {
      id
      title
      infoProyecto {
        url
        lugar
        descripcion
      }
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
}
